<?php

/**
 * @var $block \MagicToolbox\MagicZoomPlus\Block\Html\Head
 */

if (!$block->isVisibile()) return;

$jsUrl = $block->getViewFileUrl('MagicToolbox_MagicZoomPlus::js/magiczoomplus.js');
$jsPath = dirname($jsUrl);
$cssUrl = $block->getViewFileUrl('MagicToolbox_MagicZoomPlus::css/magiczoomplus.css');
$cssPath = dirname($cssUrl);

$tool = $block->magicToolboxHelper->getToolObj();
$tool->params->resetProfile();

echo $tool->getHeadersTemplate($jsPath, $cssPath);

if ($block->doDisplayMagicScrollHeaders() && ($scroll = $block->magicToolboxHelper->getScrollObj())) {
    $scroll->params->resetProfile();
    echo "\n".$scroll->getHeadersTemplate($jsPath, $cssPath, false);
}
