<?php

/**
 * @var $block \MagicToolbox\MagicZoom\Block\Html\Head
 */

if (!$block->isVisibile()) return;

$jsUrl = $block->getViewFileUrl('MagicToolbox_MagicZoom::js/magiczoom.js');
$jsPath = dirname($jsUrl);
$cssUrl = $block->getViewFileUrl('MagicToolbox_MagicZoom::css/magiczoom.css');
$cssPath = dirname($cssUrl);

$tool = $block->magicToolboxHelper->getToolObj();
$tool->params->resetProfile();

echo $tool->getHeadersTemplate($jsPath, $cssPath);

if ($block->doDisplayMagicScrollHeaders() && ($scroll = $block->magicToolboxHelper->getScrollObj())) {
    $scroll->params->resetProfile();
    echo "\n".$scroll->getHeadersTemplate($jsPath, $cssPath, false);
}
